### ISSUE TITLE
Boten kan opprette flere tråder med samme navn

### ISSUE THREAD

**Issue by rabagast** [armandg/ligabot#2]
Boten bør ikke opprette ny tråd på reddit dersom det er en med samme navn allerede.

**Comment by armandg** [comment]
Er usikker på om PRAW har en funksjon som kan sjekke dette, for har ikke klart å finne noe. Blir spennende å se om du klarer å finne ut av det.

**Comment by armandg** [comment]
Denne er tatt høyde for nå via merge-commit fra ikveld.
