### ISSUE TITLE
@rabagast: kodesjekk fra din merge

### ISSUE THREAD

**Issue by armandg** [armandg/ligabot#9]
https://github.com/armandg/ligabot/blob/a8c704ed503140e24e74d362cef6c053cdc9f9e8/ligabot-runde.py#L40#L50

Det som er på linje 40, 46 og 50, jeg regner med at det bare er søppel fra mergen jeg foretok? Er riktigtnok noob i Python, men klarer ikke å google meg fram til at noe sånt skal kunne brukes.

_____

https://github.com/armandg/ligabot/blob/a8c704ed503140e24e74d362cef6c053cdc9f9e8/ligabot-runde.py#L281-L286

Meget snasen kode, men denne gjør vel bruken av en lokal sjekk i egen tekstfil unødvendig? Spør så jeg er sikker på hvordan du tenkte at bruken av denne skulle være.

_____

https://github.com/armandg/ligabot/blob/a8c704ed503140e24e74d362cef6c053cdc9f9e8/ligabot-runde.py#L139-L143

Sånn jeg lagde koden opprinnelig, skulle 'temp_runde' klare oppgaven for både å kunne brukes som tittel på posten som ligabot sender til reddit, samt legges inn i "rundesjekk"-fila, så ligabot kan sjekke om runden har blitt posta eller ikke. Er det noen spesiell grunn til at vi må splitte opp dette til to forskjellige variabler?

**Comment by rabagast** [comment]
1. Den øverste er noe rot med mergen i Git ja. Det enkleste er å slette det som ikke trengs og commite på nytt. Jeg venter til du har en fungerende main igjen, så resetter jeg alt mitt dit. Det er litt rot på min side nå. 

2. Lokal sjekk i egen tekstfil skal være unødvendig med denne kodesnutten. Den ble skrevet litt i hui og hast uten å sjekke med deg om hvordan du ønsket å håndtere det. Dårlig kommunikasjon. Fil funker, serverkall funker. 

3. Jeg tror kanskje at renamingen ikke ble ferdig. "reddit_post_title" er for meg for forklarende enn "temp_runde". Det er ikke noe poeng med to variabler slik det er nå, så langt jeg kan se.

**Comment by armandg** [comment]
Takker, da kjører jeg en commit med rettinger basert på dette. Sletter merge-søppelet, fjerner henvisning til lokal fil for sjekk av hvilke runder som er kjørt, samt endrer navn på variabelen "temp_runde" til "reddit_post_title".
